fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "1.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "3.2.1"
    pnp4nagios:
      repo: "abstractit/pnp4nagios"
      ref: "0.1.1"
    apt:
      repo: "puppetlabs/apt"
      ref: "1.5.0"
  symlinks:
    icinga: "#{source_dir}"