name 'abstractit-icinga'
author 'Abstract IT'
version '1.2.2-rc3'
summary 'manage an icinga server'
description "manage icinga server with puppet"
project_page 'https://github.com/abstractitptyltd/puppet-icinga'
source 'https://github.com/abstractitptyltd/puppet-icinga'
license 'Apache v2 Licence'
dependency 'abstractit/pnp4nagios', '>=0.1.1'
dependency 'puppetlabs/apache', '>=1.2.0'
dependency 'puppetlabs/stdlib', '>=3.2.1'
dependency 'puppetlabs/apt', '>=1.5.0'
