name 'abstractit-icinga'
author 'abstractit'
version '1.2.2'
summary 'manage an icinga server'
description "manage icinga server with puppet"
project_page 'https://github.com/abstractitptyltd/puppet-icinga'
source 'https://github.com/abstractitptyltd/puppet-icinga'
license 'Apache v2 Licence'
dependency 'abstractit/pnp4nagios', '>=0.1.1'
dependency 'puppetlabs/apache', '>=0.10.0'
dependency 'puppetlabs/stdlib', '>=0.0.1'
dependency 'puppetlabs/apt', '>=0.0.1'
